# Generated by Django 4.1.1 on 2023-07-20 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mg_blog', '0002_magazinenew_created_at_magazinenew_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 43, 54, 865722))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 43, 54, 865722))),
            ],
        ),
        migrations.AlterField(
            model_name='magazinenew',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 43, 54, 865722)),
        ),
        migrations.AlterField(
            model_name='magazinenew',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 43, 54, 865722)),
        ),
    ]
