# Generated by Django 4.1.1 on 2023-07-20 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mg_blog', '0003_category_alter_magazinenew_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 45, 39, 512994)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 45, 39, 512994)),
        ),
        migrations.AlterField(
            model_name='magazinenew',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 45, 39, 512994)),
        ),
        migrations.AlterField(
            model_name='magazinenew',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 45, 39, 512994)),
        ),
    ]
