# Generated by Django 4.1.1 on 2023-07-20 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mg_blog', '0004_alter_category_options_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 46, 18, 216933)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 46, 18, 216933)),
        ),
        migrations.AlterField(
            model_name='magazinenew',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 46, 18, 216933)),
        ),
        migrations.AlterField(
            model_name='magazinenew',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 46, 18, 216933)),
        ),
    ]
