# Generated by Django 4.1.1 on 2023-07-20 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mg_blog', '0005_alter_category_options_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creator', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 48, 25, 258492))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 48, 25, 258492))),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.DeleteModel(
            name='magazinenew',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 48, 25, 258492)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 13, 48, 25, 258492)),
        ),
    ]
